import { NextResponse } from 'next/server';
import { revalidatePath } from 'next/cache';
import { dbConnect } from '@/lib/db';
import Blog from '@/models/Blog';
import { validate, blogSchema } from '@/lib/validation';

export async function GET() {
  await dbConnect();
  const posts = await Blog.find().sort({ createdAt: -1 });
  return NextResponse.json(posts);
}

export async function POST(request) {
  try {
    await dbConnect();
    const body = await request.json();
    const data = validate(blogSchema, body);
    // slug is auto-generated by the Blog model pre-validate hook
    const post = await Blog.create(data);
    revalidatePath('/');
    revalidatePath(`/blog/${post.slug}`, 'page');
    return NextResponse.json(post, { status: 201 });
  } catch (err) {
    if (err.status === 400) return NextResponse.json({ error: err.message, details: err.details }, { status: 400 });
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
